// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySanBong.Data;

#nullable disable

namespace QuanLySanBong.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySanBong.Entities.Account.Model.AccountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("int");

                    b.Property<int?>("IdStaff")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomer")
                        .IsUnique()
                        .HasFilter("[IdCustomer] IS NOT NULL");

                    b.HasIndex("IdStaff")
                        .IsUnique()
                        .HasFilter("[IdStaff] IS NOT NULL");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin",
                            Password = "$2a$11$u1viFQcjmo9wxYQiHdh93ekvlVhdt1Uhjgt/24J/zK31Rx3TlXjYG",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Bill.Model.BillModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("IdBooking")
                        .HasColumnType("int");

                    b.Property<int?>("IdPaidBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("IdBooking")
                        .IsUnique();

                    b.HasIndex("IdPaidBy");

                    b.ToTable("Bill", (string)null);
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Booking.Model.BookingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("int");

                    b.Property<int>("IdPitch")
                        .HasColumnType("int");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("IdPitch");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Customer.Model.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Pitch.Model.PitchModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("IdPitchType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("IdPitchType");

                    b.ToTable("Pitch", (string)null);
                });

            modelBuilder.Entity("QuanLySanBong.Entities.PitchType.Model.PitchTypeImageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PitchTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PitchTypeId");

                    b.ToTable("PitchTypeImage", (string)null);
                });

            modelBuilder.Entity("QuanLySanBong.Entities.PitchType.Model.PitchTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LimitPerson")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PitchType", (string)null);
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Staff.Model.StaffModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Account.Model.AccountModel", b =>
                {
                    b.HasOne("QuanLySanBong.Entities.Customer.Model.CustomerModel", "Customer")
                        .WithOne("Account")
                        .HasForeignKey("QuanLySanBong.Entities.Account.Model.AccountModel", "IdCustomer");

                    b.HasOne("QuanLySanBong.Entities.Staff.Model.StaffModel", "Staff")
                        .WithOne("Account")
                        .HasForeignKey("QuanLySanBong.Entities.Account.Model.AccountModel", "IdStaff");

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Bill.Model.BillModel", b =>
                {
                    b.HasOne("QuanLySanBong.Entities.Booking.Model.BookingModel", "Booking")
                        .WithOne("Bill")
                        .HasForeignKey("QuanLySanBong.Entities.Bill.Model.BillModel", "IdBooking")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySanBong.Entities.Account.Model.AccountModel", "PaidBy")
                        .WithMany()
                        .HasForeignKey("IdPaidBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("PaidBy");
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Booking.Model.BookingModel", b =>
                {
                    b.HasOne("QuanLySanBong.Entities.Customer.Model.CustomerModel", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLySanBong.Entities.Pitch.Model.PitchModel", "Pitch")
                        .WithMany("Bookings")
                        .HasForeignKey("IdPitch")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Pitch");
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Pitch.Model.PitchModel", b =>
                {
                    b.HasOne("QuanLySanBong.Entities.PitchType.Model.PitchTypeModel", "PitchType")
                        .WithMany("Pitches")
                        .HasForeignKey("IdPitchType")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PitchType");
                });

            modelBuilder.Entity("QuanLySanBong.Entities.PitchType.Model.PitchTypeImageModel", b =>
                {
                    b.HasOne("QuanLySanBong.Entities.PitchType.Model.PitchTypeModel", "PitchType")
                        .WithMany("Images")
                        .HasForeignKey("PitchTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PitchType");
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Booking.Model.BookingModel", b =>
                {
                    b.Navigation("Bill")
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Customer.Model.CustomerModel", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Pitch.Model.PitchModel", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("QuanLySanBong.Entities.PitchType.Model.PitchTypeModel", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Pitches");
                });

            modelBuilder.Entity("QuanLySanBong.Entities.Staff.Model.StaffModel", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
